<a href="https://colab.research.google.com/github/komlalex/Basic_API/blob/main/1_Intro_To_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TensorFlow 2.0 Introductions**


In this notebook, you will be given an Introduction to TensorFlow 2.0. We will walk through the following topics within the module:


*   TensorFlow install and setup
*   Representing Tensors
*   Tensor Shape and Rank
*   Types of Tensors



TensorFlow is an open source machine learning platform. It is owned and maintained by google and is one of the largest open source learning lbraries in the world.
For our purpose, we will use TensorFlow to build models that can do some of the following things:


*   Image Classification
*   Data Clustering
*   Regression
*   Reinforcement Learning
*   Natural Language Processing







# How it Works
TensorFlow has two main components that we'll try to understand:


*   Graphs
*   Sessions

TensorFlow works by building a graph of defined computations. Nothing is computed or stored in the graph. It is simply a way of defining the operations that have been written in the code.

A TensorFlow session allows parts of the graph to be executed. It allocates memory and resources and handles the execution of the operations and computations we've defined.

In some instances, we will need to run a session to be able to execute parts of the graph we've created.



In [4]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Tensors
A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes.

It shouldn't surprise you that tensors are a fundamental aspect of TensorFlow. They are the main objects that are passed around and manipulated throughout the program. Each tensor represents a partially defined computation that will eventually produce a value. TensorFlwo programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the grpah allows results to be generated.
Each tensor has a data type and shape.
**Data Types include**: float32, int32, string and others.
**Shape**: Represents the dimension of the data

# Creating Tensors
Below are examples of how to create some different tensors.


In [10]:
string = tf.Variable("this is a string", dtype= tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.456, tf.float64)

# Rank/Degree

Another word for rank is degree. These terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar.
Now, we'll create some tensors of higher degress/ranks.

In [17]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["Test", "Ok"], ["Test", "Yes"]], tf.string)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

**To determine the rank of a tensor, we can call the following method**

In [15]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape of Tensors

Now that we've talked about the rank of tensors, it's time to talk about the shape. The shape of a tensor is imply the amount of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes, it may be unknown.

**To get the shape of a tensor, we can use the shape attribute**

In [ ]:
rank2_tensor.shape

# Changing Shape
The number of elements in a tensor is the product of the sizes of all of it's shapes. There are often many shapes that have the same number of elements, making it convenient to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [26]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor1, [3, -1])
print(tensor3)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


Now let's have a look at our different tensors.

In [ ]:
print(tensor1)
print(tensor2)
print(tensor3)

# Types of Tensors

These are the most commonly used types of tensors and we will talk more in depth about each as they are used.


*   Variable
*   Constant
*   Placeholder
*   SparseTensor

With the exception of variables, all these types of tensors are immutable, meaning their value may not change during execution.
For now, it us suffiecient that we use **Variable** tensor when we want to potentially change the value of our tensor.


# Evaluating Tensors

There will be times throughout this guide that we need to valuate a tensor. In other words, get its value. Since tensors represent a partially complete computation, we will need to run what's called a session to evaluate the tensor.

There are many different ways to achieve this but the simplest way is shown below.

In [31]:
with tf.compat.v1.Session() as sess:
  constant = tf.constant([1,2,3])
  tft = constant * constant
  print(tft.eval())

[1 4 9]


In [34]:
t = tf.zeros([5,5,5,5])
t = tf.reshape(t, [125, -1])
print(t)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]