<a href="https://colab.research.google.com/github/komlalex/Basic_API/blob/main/Tensor_Basicsl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
#physical_devices = tf.config.list_logical_devices("GPU")
#tf.config.experimental.set_memory_growth(physical_devices[0], True)

**Initialization of Tensors**

In [21]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
x = tf.constant([[1,2,3], [4,5,6]])
x = tf.constant(True)
x = tf.constant("Hello")

x = tf.ones((3,2))
x = tf.zeros((2,3))
x = tf.eye(3) # I for identity matrix (eye)

x = tf.random.normal((3,3), mean=0, stddev=1)
x = tf.random.uniform((1,3), minval=0, maxval=1)
x = tf.range(start=1, limit=10, delta=2)


# Converting between different types
tf.cast(x, dtype=tf.float64)
# tf.float(16, 32, 64), tf.int(8, 16, 32, 64), tf.bool( )


print(x)

tf.Tensor(b'Hello', shape=(), dtype=string)


**Mathematical Operations**

In [35]:

x  = tf.constant([1,2,3])
y = tf.constant([9,8,7])

# Add
z = tf.add(x, y)
z = x + y

# Subtract
z = tf.subtract(x, y)
z = x - y

# Divide
z = tf.divide(x, y)
z = x / y

# Multiply
z = tf.multiply(x, y)
z = x * y

# Dot Product
z = tf.tensordot(x, y, axes=1)
z = tf.reduce_sum(x*y, axis=0)

# Exponentiation
z = x ** 5


x = tf.random.normal((2,3))
y= tf.random.normal((3,4))
z = tf.matmul(x, y)
print(z)
z = x @ y
print(z)

tf.Tensor(
[[-0.29586878  0.02551367 -0.89939845  1.0395887 ]
 [ 0.3593284   1.6788232  -0.4187169   0.18697488]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-0.29586878  0.02551367 -0.89939845  1.0395887 ]
 [ 0.3593284   1.6788232  -0.4187169   0.18697488]], shape=(2, 4), dtype=float32)


**Indexing**

In [28]:
x = tf.constant([0,1,1,2,3,1,2,3])
#print(x[:])
#print(x[1:])
#print(x[1:3])
#print(x[::2])
#print(x[::-1])
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)

x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
print(x[1, :])
print(x[0:2])


tf.Tensor([3 4], shape=(2,), dtype=int32)


**Reshaping**

In [33]:
 x = tf.range(9)
 x = tf.reshape( x, shape=(3,3))
 x = tf.transpose(x, perm=[1,0])
 print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
